server:
  port: 8800
spring:
  application:
    name: cloud-eureka-movie
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.116.128
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8880/eureka/